package com.jiuyescm.bms.pub.shop.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShopEntityExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public ShopEntityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andShopidIsNull() {
			addCriterion("shopid is null");
			return (Criteria) this;
		}

		public Criteria andShopidIsNotNull() {
			addCriterion("shopid is not null");
			return (Criteria) this;
		}

		public Criteria andShopidEqualTo(String value) {
			addCriterion("shopid =", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidNotEqualTo(String value) {
			addCriterion("shopid <>", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidGreaterThan(String value) {
			addCriterion("shopid >", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidGreaterThanOrEqualTo(String value) {
			addCriterion("shopid >=", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidLessThan(String value) {
			addCriterion("shopid <", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidLessThanOrEqualTo(String value) {
			addCriterion("shopid <=", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidLike(String value) {
			addCriterion("shopid like", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidNotLike(String value) {
			addCriterion("shopid not like", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidIn(List<String> values) {
			addCriterion("shopid in", values, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidNotIn(List<String> values) {
			addCriterion("shopid not in", values, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidBetween(String value1, String value2) {
			addCriterion("shopid between", value1, value2, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidNotBetween(String value1, String value2) {
			addCriterion("shopid not between", value1, value2, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopnameIsNull() {
			addCriterion("shopname is null");
			return (Criteria) this;
		}

		public Criteria andShopnameIsNotNull() {
			addCriterion("shopname is not null");
			return (Criteria) this;
		}

		public Criteria andShopnameEqualTo(String value) {
			addCriterion("shopname =", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameNotEqualTo(String value) {
			addCriterion("shopname <>", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameGreaterThan(String value) {
			addCriterion("shopname >", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameGreaterThanOrEqualTo(String value) {
			addCriterion("shopname >=", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameLessThan(String value) {
			addCriterion("shopname <", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameLessThanOrEqualTo(String value) {
			addCriterion("shopname <=", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameLike(String value) {
			addCriterion("shopname like", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameNotLike(String value) {
			addCriterion("shopname not like", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameIn(List<String> values) {
			addCriterion("shopname in", values, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameNotIn(List<String> values) {
			addCriterion("shopname not in", values, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameBetween(String value1, String value2) {
			addCriterion("shopname between", value1, value2, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameNotBetween(String value1, String value2) {
			addCriterion("shopname not between", value1, value2, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopcodeIsNull() {
			addCriterion("shopcode is null");
			return (Criteria) this;
		}

		public Criteria andShopcodeIsNotNull() {
			addCriterion("shopcode is not null");
			return (Criteria) this;
		}

		public Criteria andShopcodeEqualTo(String value) {
			addCriterion("shopcode =", value, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeNotEqualTo(String value) {
			addCriterion("shopcode <>", value, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeGreaterThan(String value) {
			addCriterion("shopcode >", value, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeGreaterThanOrEqualTo(String value) {
			addCriterion("shopcode >=", value, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeLessThan(String value) {
			addCriterion("shopcode <", value, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeLessThanOrEqualTo(String value) {
			addCriterion("shopcode <=", value, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeLike(String value) {
			addCriterion("shopcode like", value, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeNotLike(String value) {
			addCriterion("shopcode not like", value, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeIn(List<String> values) {
			addCriterion("shopcode in", values, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeNotIn(List<String> values) {
			addCriterion("shopcode not in", values, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeBetween(String value1, String value2) {
			addCriterion("shopcode between", value1, value2, "shopcode");
			return (Criteria) this;
		}

		public Criteria andShopcodeNotBetween(String value1, String value2) {
			addCriterion("shopcode not between", value1, value2, "shopcode");
			return (Criteria) this;
		}

		public Criteria andPlatformidIsNull() {
			addCriterion("platformid is null");
			return (Criteria) this;
		}

		public Criteria andPlatformidIsNotNull() {
			addCriterion("platformid is not null");
			return (Criteria) this;
		}

		public Criteria andPlatformidEqualTo(Integer value) {
			addCriterion("platformid =", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidNotEqualTo(Integer value) {
			addCriterion("platformid <>", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidGreaterThan(Integer value) {
			addCriterion("platformid >", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidGreaterThanOrEqualTo(Integer value) {
			addCriterion("platformid >=", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidLessThan(Integer value) {
			addCriterion("platformid <", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidLessThanOrEqualTo(Integer value) {
			addCriterion("platformid <=", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidIn(List<Integer> values) {
			addCriterion("platformid in", values, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidNotIn(List<Integer> values) {
			addCriterion("platformid not in", values, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidBetween(Integer value1, Integer value2) {
			addCriterion("platformid between", value1, value2, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidNotBetween(Integer value1, Integer value2) {
			addCriterion("platformid not between", value1, value2, "platformid");
			return (Criteria) this;
		}

		public Criteria andShopaccountIsNull() {
			addCriterion("shopaccount is null");
			return (Criteria) this;
		}

		public Criteria andShopaccountIsNotNull() {
			addCriterion("shopaccount is not null");
			return (Criteria) this;
		}

		public Criteria andShopaccountEqualTo(String value) {
			addCriterion("shopaccount =", value, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountNotEqualTo(String value) {
			addCriterion("shopaccount <>", value, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountGreaterThan(String value) {
			addCriterion("shopaccount >", value, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountGreaterThanOrEqualTo(String value) {
			addCriterion("shopaccount >=", value, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountLessThan(String value) {
			addCriterion("shopaccount <", value, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountLessThanOrEqualTo(String value) {
			addCriterion("shopaccount <=", value, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountLike(String value) {
			addCriterion("shopaccount like", value, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountNotLike(String value) {
			addCriterion("shopaccount not like", value, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountIn(List<String> values) {
			addCriterion("shopaccount in", values, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountNotIn(List<String> values) {
			addCriterion("shopaccount not in", values, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountBetween(String value1, String value2) {
			addCriterion("shopaccount between", value1, value2, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShopaccountNotBetween(String value1, String value2) {
			addCriterion("shopaccount not between", value1, value2, "shopaccount");
			return (Criteria) this;
		}

		public Criteria andShoppwdIsNull() {
			addCriterion("shoppwd is null");
			return (Criteria) this;
		}

		public Criteria andShoppwdIsNotNull() {
			addCriterion("shoppwd is not null");
			return (Criteria) this;
		}

		public Criteria andShoppwdEqualTo(String value) {
			addCriterion("shoppwd =", value, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdNotEqualTo(String value) {
			addCriterion("shoppwd <>", value, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdGreaterThan(String value) {
			addCriterion("shoppwd >", value, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdGreaterThanOrEqualTo(String value) {
			addCriterion("shoppwd >=", value, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdLessThan(String value) {
			addCriterion("shoppwd <", value, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdLessThanOrEqualTo(String value) {
			addCriterion("shoppwd <=", value, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdLike(String value) {
			addCriterion("shoppwd like", value, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdNotLike(String value) {
			addCriterion("shoppwd not like", value, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdIn(List<String> values) {
			addCriterion("shoppwd in", values, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdNotIn(List<String> values) {
			addCriterion("shoppwd not in", values, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdBetween(String value1, String value2) {
			addCriterion("shoppwd between", value1, value2, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andShoppwdNotBetween(String value1, String value2) {
			addCriterion("shoppwd not between", value1, value2, "shoppwd");
			return (Criteria) this;
		}

		public Criteria andLinkmanIsNull() {
			addCriterion("linkman is null");
			return (Criteria) this;
		}

		public Criteria andLinkmanIsNotNull() {
			addCriterion("linkman is not null");
			return (Criteria) this;
		}

		public Criteria andLinkmanEqualTo(String value) {
			addCriterion("linkman =", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanNotEqualTo(String value) {
			addCriterion("linkman <>", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanGreaterThan(String value) {
			addCriterion("linkman >", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanGreaterThanOrEqualTo(String value) {
			addCriterion("linkman >=", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanLessThan(String value) {
			addCriterion("linkman <", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanLessThanOrEqualTo(String value) {
			addCriterion("linkman <=", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanLike(String value) {
			addCriterion("linkman like", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanNotLike(String value) {
			addCriterion("linkman not like", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanIn(List<String> values) {
			addCriterion("linkman in", values, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanNotIn(List<String> values) {
			addCriterion("linkman not in", values, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanBetween(String value1, String value2) {
			addCriterion("linkman between", value1, value2, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanNotBetween(String value1, String value2) {
			addCriterion("linkman not between", value1, value2, "linkman");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("tel is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("tel is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("tel =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("tel <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("tel >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("tel >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("tel <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("tel <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("tel like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("tel not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("tel in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("tel not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("tel between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("tel not between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andZipcodeIsNull() {
			addCriterion("zipcode is null");
			return (Criteria) this;
		}

		public Criteria andZipcodeIsNotNull() {
			addCriterion("zipcode is not null");
			return (Criteria) this;
		}

		public Criteria andZipcodeEqualTo(String value) {
			addCriterion("zipcode =", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeNotEqualTo(String value) {
			addCriterion("zipcode <>", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeGreaterThan(String value) {
			addCriterion("zipcode >", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
			addCriterion("zipcode >=", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeLessThan(String value) {
			addCriterion("zipcode <", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeLessThanOrEqualTo(String value) {
			addCriterion("zipcode <=", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeLike(String value) {
			addCriterion("zipcode like", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeNotLike(String value) {
			addCriterion("zipcode not like", value, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeIn(List<String> values) {
			addCriterion("zipcode in", values, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeNotIn(List<String> values) {
			addCriterion("zipcode not in", values, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeBetween(String value1, String value2) {
			addCriterion("zipcode between", value1, value2, "zipcode");
			return (Criteria) this;
		}

		public Criteria andZipcodeNotBetween(String value1, String value2) {
			addCriterion("zipcode not between", value1, value2, "zipcode");
			return (Criteria) this;
		}

		public Criteria andDelflagIsNull() {
			addCriterion("delflag is null");
			return (Criteria) this;
		}

		public Criteria andDelflagIsNotNull() {
			addCriterion("delflag is not null");
			return (Criteria) this;
		}

		public Criteria andDelflagEqualTo(Integer value) {
			addCriterion("delflag =", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotEqualTo(Integer value) {
			addCriterion("delflag <>", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagGreaterThan(Integer value) {
			addCriterion("delflag >", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("delflag >=", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagLessThan(Integer value) {
			addCriterion("delflag <", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagLessThanOrEqualTo(Integer value) {
			addCriterion("delflag <=", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagIn(List<Integer> values) {
			addCriterion("delflag in", values, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotIn(List<Integer> values) {
			addCriterion("delflag not in", values, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagBetween(Integer value1, Integer value2) {
			addCriterion("delflag between", value1, value2, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotBetween(Integer value1, Integer value2) {
			addCriterion("delflag not between", value1, value2, "delflag");
			return (Criteria) this;
		}

		public Criteria andCrepersonidIsNull() {
			addCriterion("crepersonid is null");
			return (Criteria) this;
		}

		public Criteria andCrepersonidIsNotNull() {
			addCriterion("crepersonid is not null");
			return (Criteria) this;
		}

		public Criteria andCrepersonidEqualTo(String value) {
			addCriterion("crepersonid =", value, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidNotEqualTo(String value) {
			addCriterion("crepersonid <>", value, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidGreaterThan(String value) {
			addCriterion("crepersonid >", value, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidGreaterThanOrEqualTo(String value) {
			addCriterion("crepersonid >=", value, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidLessThan(String value) {
			addCriterion("crepersonid <", value, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidLessThanOrEqualTo(String value) {
			addCriterion("crepersonid <=", value, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidLike(String value) {
			addCriterion("crepersonid like", value, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidNotLike(String value) {
			addCriterion("crepersonid not like", value, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidIn(List<String> values) {
			addCriterion("crepersonid in", values, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidNotIn(List<String> values) {
			addCriterion("crepersonid not in", values, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidBetween(String value1, String value2) {
			addCriterion("crepersonid between", value1, value2, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonidNotBetween(String value1, String value2) {
			addCriterion("crepersonid not between", value1, value2, "crepersonid");
			return (Criteria) this;
		}

		public Criteria andCrepersonIsNull() {
			addCriterion("creperson is null");
			return (Criteria) this;
		}

		public Criteria andCrepersonIsNotNull() {
			addCriterion("creperson is not null");
			return (Criteria) this;
		}

		public Criteria andCrepersonEqualTo(String value) {
			addCriterion("creperson =", value, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonNotEqualTo(String value) {
			addCriterion("creperson <>", value, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonGreaterThan(String value) {
			addCriterion("creperson >", value, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonGreaterThanOrEqualTo(String value) {
			addCriterion("creperson >=", value, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonLessThan(String value) {
			addCriterion("creperson <", value, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonLessThanOrEqualTo(String value) {
			addCriterion("creperson <=", value, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonLike(String value) {
			addCriterion("creperson like", value, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonNotLike(String value) {
			addCriterion("creperson not like", value, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonIn(List<String> values) {
			addCriterion("creperson in", values, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonNotIn(List<String> values) {
			addCriterion("creperson not in", values, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonBetween(String value1, String value2) {
			addCriterion("creperson between", value1, value2, "creperson");
			return (Criteria) this;
		}

		public Criteria andCrepersonNotBetween(String value1, String value2) {
			addCriterion("creperson not between", value1, value2, "creperson");
			return (Criteria) this;
		}

		public Criteria andCretimeIsNull() {
			addCriterion("cretime is null");
			return (Criteria) this;
		}

		public Criteria andCretimeIsNotNull() {
			addCriterion("cretime is not null");
			return (Criteria) this;
		}

		public Criteria andCretimeEqualTo(Date value) {
			addCriterion("cretime =", value, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeNotEqualTo(Date value) {
			addCriterion("cretime <>", value, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeGreaterThan(Date value) {
			addCriterion("cretime >", value, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeGreaterThanOrEqualTo(Date value) {
			addCriterion("cretime >=", value, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeLessThan(Date value) {
			addCriterion("cretime <", value, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeLessThanOrEqualTo(Date value) {
			addCriterion("cretime <=", value, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeIn(List<Date> values) {
			addCriterion("cretime in", values, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeNotIn(List<Date> values) {
			addCriterion("cretime not in", values, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeBetween(Date value1, Date value2) {
			addCriterion("cretime between", value1, value2, "cretime");
			return (Criteria) this;
		}

		public Criteria andCretimeNotBetween(Date value1, Date value2) {
			addCriterion("cretime not between", value1, value2, "cretime");
			return (Criteria) this;
		}

		public Criteria andModpersonidIsNull() {
			addCriterion("modpersonid is null");
			return (Criteria) this;
		}

		public Criteria andModpersonidIsNotNull() {
			addCriterion("modpersonid is not null");
			return (Criteria) this;
		}

		public Criteria andModpersonidEqualTo(String value) {
			addCriterion("modpersonid =", value, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidNotEqualTo(String value) {
			addCriterion("modpersonid <>", value, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidGreaterThan(String value) {
			addCriterion("modpersonid >", value, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidGreaterThanOrEqualTo(String value) {
			addCriterion("modpersonid >=", value, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidLessThan(String value) {
			addCriterion("modpersonid <", value, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidLessThanOrEqualTo(String value) {
			addCriterion("modpersonid <=", value, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidLike(String value) {
			addCriterion("modpersonid like", value, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidNotLike(String value) {
			addCriterion("modpersonid not like", value, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidIn(List<String> values) {
			addCriterion("modpersonid in", values, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidNotIn(List<String> values) {
			addCriterion("modpersonid not in", values, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidBetween(String value1, String value2) {
			addCriterion("modpersonid between", value1, value2, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonidNotBetween(String value1, String value2) {
			addCriterion("modpersonid not between", value1, value2, "modpersonid");
			return (Criteria) this;
		}

		public Criteria andModpersonIsNull() {
			addCriterion("modperson is null");
			return (Criteria) this;
		}

		public Criteria andModpersonIsNotNull() {
			addCriterion("modperson is not null");
			return (Criteria) this;
		}

		public Criteria andModpersonEqualTo(String value) {
			addCriterion("modperson =", value, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonNotEqualTo(String value) {
			addCriterion("modperson <>", value, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonGreaterThan(String value) {
			addCriterion("modperson >", value, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonGreaterThanOrEqualTo(String value) {
			addCriterion("modperson >=", value, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonLessThan(String value) {
			addCriterion("modperson <", value, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonLessThanOrEqualTo(String value) {
			addCriterion("modperson <=", value, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonLike(String value) {
			addCriterion("modperson like", value, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonNotLike(String value) {
			addCriterion("modperson not like", value, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonIn(List<String> values) {
			addCriterion("modperson in", values, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonNotIn(List<String> values) {
			addCriterion("modperson not in", values, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonBetween(String value1, String value2) {
			addCriterion("modperson between", value1, value2, "modperson");
			return (Criteria) this;
		}

		public Criteria andModpersonNotBetween(String value1, String value2) {
			addCriterion("modperson not between", value1, value2, "modperson");
			return (Criteria) this;
		}

		public Criteria andModtimeIsNull() {
			addCriterion("modtime is null");
			return (Criteria) this;
		}

		public Criteria andModtimeIsNotNull() {
			addCriterion("modtime is not null");
			return (Criteria) this;
		}

		public Criteria andModtimeEqualTo(Date value) {
			addCriterion("modtime =", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeNotEqualTo(Date value) {
			addCriterion("modtime <>", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeGreaterThan(Date value) {
			addCriterion("modtime >", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modtime >=", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeLessThan(Date value) {
			addCriterion("modtime <", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeLessThanOrEqualTo(Date value) {
			addCriterion("modtime <=", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeIn(List<Date> values) {
			addCriterion("modtime in", values, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeNotIn(List<Date> values) {
			addCriterion("modtime not in", values, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeBetween(Date value1, Date value2) {
			addCriterion("modtime between", value1, value2, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeNotBetween(Date value1, Date value2) {
			addCriterion("modtime not between", value1, value2, "modtime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table pub_shop
	 * 
	 * @mbggenerated do_not_delete_during_merge Mon Sep 07 21:36:05 CST 2015
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table pub_shop
	 * 
	 * @mbggenerated Mon Sep 07 21:36:05 CST 2015
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}