package com.jiuyescm.bms.pub.waybill.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WaybillsetEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public WaybillsetEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWaybillnoIsNull() {
            addCriterion("waybillno is null");
            return (Criteria) this;
        }

        public Criteria andWaybillnoIsNotNull() {
            addCriterion("waybillno is not null");
            return (Criteria) this;
        }

        public Criteria andWaybillnoEqualTo(String value) {
            addCriterion("waybillno =", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoNotEqualTo(String value) {
            addCriterion("waybillno <>", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoGreaterThan(String value) {
            addCriterion("waybillno >", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoGreaterThanOrEqualTo(String value) {
            addCriterion("waybillno >=", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoLessThan(String value) {
            addCriterion("waybillno <", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoLessThanOrEqualTo(String value) {
            addCriterion("waybillno <=", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoLike(String value) {
            addCriterion("waybillno like", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoNotLike(String value) {
            addCriterion("waybillno not like", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoIn(List<String> values) {
            addCriterion("waybillno in", values, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoNotIn(List<String> values) {
            addCriterion("waybillno not in", values, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoBetween(String value1, String value2) {
            addCriterion("waybillno between", value1, value2, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoNotBetween(String value1, String value2) {
            addCriterion("waybillno not between", value1, value2, "waybillno");
            return (Criteria) this;
        }

        public Criteria andIsuseIsNull() {
            addCriterion("isuse is null");
            return (Criteria) this;
        }

        public Criteria andIsuseIsNotNull() {
            addCriterion("isuse is not null");
            return (Criteria) this;
        }

        public Criteria andIsuseEqualTo(Short value) {
            addCriterion("isuse =", value, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseNotEqualTo(Short value) {
            addCriterion("isuse <>", value, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseGreaterThan(Short value) {
            addCriterion("isuse >", value, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseGreaterThanOrEqualTo(Short value) {
            addCriterion("isuse >=", value, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseLessThan(Short value) {
            addCriterion("isuse <", value, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseLessThanOrEqualTo(Short value) {
            addCriterion("isuse <=", value, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseIn(List<Short> values) {
            addCriterion("isuse in", values, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseNotIn(List<Short> values) {
            addCriterion("isuse not in", values, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseBetween(Short value1, Short value2) {
            addCriterion("isuse between", value1, value2, "isuse");
            return (Criteria) this;
        }

        public Criteria andIsuseNotBetween(Short value1, Short value2) {
            addCriterion("isuse not between", value1, value2, "isuse");
            return (Criteria) this;
        }

        public Criteria andSerialnumberIsNull() {
            addCriterion("serialnumber is null");
            return (Criteria) this;
        }

        public Criteria andSerialnumberIsNotNull() {
            addCriterion("serialnumber is not null");
            return (Criteria) this;
        }

        public Criteria andSerialnumberEqualTo(Long value) {
            addCriterion("serialnumber =", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberNotEqualTo(Long value) {
            addCriterion("serialnumber <>", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberGreaterThan(Long value) {
            addCriterion("serialnumber >", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberGreaterThanOrEqualTo(Long value) {
            addCriterion("serialnumber >=", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberLessThan(Long value) {
            addCriterion("serialnumber <", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberLessThanOrEqualTo(Long value) {
            addCriterion("serialnumber <=", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberIn(List<Long> values) {
            addCriterion("serialnumber in", values, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberNotIn(List<Long> values) {
            addCriterion("serialnumber not in", values, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberBetween(Long value1, Long value2) {
            addCriterion("serialnumber between", value1, value2, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberNotBetween(Long value1, Long value2) {
            addCriterion("serialnumber not between", value1, value2, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNull() {
            addCriterion("delflag is null");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNotNull() {
            addCriterion("delflag is not null");
            return (Criteria) this;
        }

        public Criteria andDelflagEqualTo(Short value) {
            addCriterion("delflag =", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotEqualTo(Short value) {
            addCriterion("delflag <>", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThan(Short value) {
            addCriterion("delflag >", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThanOrEqualTo(Short value) {
            addCriterion("delflag >=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThan(Short value) {
            addCriterion("delflag <", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThanOrEqualTo(Short value) {
            addCriterion("delflag <=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagIn(List<Short> values) {
            addCriterion("delflag in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotIn(List<Short> values) {
            addCriterion("delflag not in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagBetween(Short value1, Short value2) {
            addCriterion("delflag between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotBetween(Short value1, Short value2) {
            addCriterion("delflag not between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andBilltypeIsNull() {
            addCriterion("billtype is null");
            return (Criteria) this;
        }

        public Criteria andBilltypeIsNotNull() {
            addCriterion("billtype is not null");
            return (Criteria) this;
        }

        public Criteria andBilltypeEqualTo(String value) {
            addCriterion("billtype =", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotEqualTo(String value) {
            addCriterion("billtype <>", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeGreaterThan(String value) {
            addCriterion("billtype >", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeGreaterThanOrEqualTo(String value) {
            addCriterion("billtype >=", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLessThan(String value) {
            addCriterion("billtype <", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLessThanOrEqualTo(String value) {
            addCriterion("billtype <=", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeLike(String value) {
            addCriterion("billtype like", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotLike(String value) {
            addCriterion("billtype not like", value, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeIn(List<String> values) {
            addCriterion("billtype in", values, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotIn(List<String> values) {
            addCriterion("billtype not in", values, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeBetween(String value1, String value2) {
            addCriterion("billtype between", value1, value2, "billtype");
            return (Criteria) this;
        }

        public Criteria andBilltypeNotBetween(String value1, String value2) {
            addCriterion("billtype not between", value1, value2, "billtype");
            return (Criteria) this;
        }

        public Criteria andDonoIsNull() {
            addCriterion("dono is null");
            return (Criteria) this;
        }

        public Criteria andDonoIsNotNull() {
            addCriterion("dono is not null");
            return (Criteria) this;
        }

        public Criteria andDonoEqualTo(String value) {
            addCriterion("dono =", value, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoNotEqualTo(String value) {
            addCriterion("dono <>", value, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoGreaterThan(String value) {
            addCriterion("dono >", value, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoGreaterThanOrEqualTo(String value) {
            addCriterion("dono >=", value, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoLessThan(String value) {
            addCriterion("dono <", value, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoLessThanOrEqualTo(String value) {
            addCriterion("dono <=", value, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoLike(String value) {
            addCriterion("dono like", value, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoNotLike(String value) {
            addCriterion("dono not like", value, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoIn(List<String> values) {
            addCriterion("dono in", values, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoNotIn(List<String> values) {
            addCriterion("dono not in", values, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoBetween(String value1, String value2) {
            addCriterion("dono between", value1, value2, "dono");
            return (Criteria) this;
        }

        public Criteria andDonoNotBetween(String value1, String value2) {
            addCriterion("dono not between", value1, value2, "dono");
            return (Criteria) this;
        }

        public Criteria andCrepersonIsNull() {
            addCriterion("creperson is null");
            return (Criteria) this;
        }

        public Criteria andCrepersonIsNotNull() {
            addCriterion("creperson is not null");
            return (Criteria) this;
        }

        public Criteria andCrepersonEqualTo(String value) {
            addCriterion("creperson =", value, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonNotEqualTo(String value) {
            addCriterion("creperson <>", value, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonGreaterThan(String value) {
            addCriterion("creperson >", value, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonGreaterThanOrEqualTo(String value) {
            addCriterion("creperson >=", value, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonLessThan(String value) {
            addCriterion("creperson <", value, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonLessThanOrEqualTo(String value) {
            addCriterion("creperson <=", value, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonLike(String value) {
            addCriterion("creperson like", value, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonNotLike(String value) {
            addCriterion("creperson not like", value, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonIn(List<String> values) {
            addCriterion("creperson in", values, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonNotIn(List<String> values) {
            addCriterion("creperson not in", values, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonBetween(String value1, String value2) {
            addCriterion("creperson between", value1, value2, "creperson");
            return (Criteria) this;
        }

        public Criteria andCrepersonNotBetween(String value1, String value2) {
            addCriterion("creperson not between", value1, value2, "creperson");
            return (Criteria) this;
        }

        public Criteria andCretimeIsNull() {
            addCriterion("cretime is null");
            return (Criteria) this;
        }

        public Criteria andCretimeIsNotNull() {
            addCriterion("cretime is not null");
            return (Criteria) this;
        }

        public Criteria andCretimeEqualTo(Date value) {
            addCriterion("cretime =", value, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeNotEqualTo(Date value) {
            addCriterion("cretime <>", value, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeGreaterThan(Date value) {
            addCriterion("cretime >", value, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cretime >=", value, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeLessThan(Date value) {
            addCriterion("cretime <", value, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeLessThanOrEqualTo(Date value) {
            addCriterion("cretime <=", value, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeIn(List<Date> values) {
            addCriterion("cretime in", values, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeNotIn(List<Date> values) {
            addCriterion("cretime not in", values, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeBetween(Date value1, Date value2) {
            addCriterion("cretime between", value1, value2, "cretime");
            return (Criteria) this;
        }

        public Criteria andCretimeNotBetween(Date value1, Date value2) {
            addCriterion("cretime not between", value1, value2, "cretime");
            return (Criteria) this;
        }

        public Criteria andModpersonIsNull() {
            addCriterion("modperson is null");
            return (Criteria) this;
        }

        public Criteria andModpersonIsNotNull() {
            addCriterion("modperson is not null");
            return (Criteria) this;
        }

        public Criteria andModpersonEqualTo(String value) {
            addCriterion("modperson =", value, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonNotEqualTo(String value) {
            addCriterion("modperson <>", value, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonGreaterThan(String value) {
            addCriterion("modperson >", value, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonGreaterThanOrEqualTo(String value) {
            addCriterion("modperson >=", value, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonLessThan(String value) {
            addCriterion("modperson <", value, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonLessThanOrEqualTo(String value) {
            addCriterion("modperson <=", value, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonLike(String value) {
            addCriterion("modperson like", value, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonNotLike(String value) {
            addCriterion("modperson not like", value, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonIn(List<String> values) {
            addCriterion("modperson in", values, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonNotIn(List<String> values) {
            addCriterion("modperson not in", values, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonBetween(String value1, String value2) {
            addCriterion("modperson between", value1, value2, "modperson");
            return (Criteria) this;
        }

        public Criteria andModpersonNotBetween(String value1, String value2) {
            addCriterion("modperson not between", value1, value2, "modperson");
            return (Criteria) this;
        }

        public Criteria andModtimeIsNull() {
            addCriterion("modtime is null");
            return (Criteria) this;
        }

        public Criteria andModtimeIsNotNull() {
            addCriterion("modtime is not null");
            return (Criteria) this;
        }

        public Criteria andModtimeEqualTo(Date value) {
            addCriterion("modtime =", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotEqualTo(Date value) {
            addCriterion("modtime <>", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeGreaterThan(Date value) {
            addCriterion("modtime >", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modtime >=", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeLessThan(Date value) {
            addCriterion("modtime <", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeLessThanOrEqualTo(Date value) {
            addCriterion("modtime <=", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeIn(List<Date> values) {
            addCriterion("modtime in", values, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotIn(List<Date> values) {
            addCriterion("modtime not in", values, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeBetween(Date value1, Date value2) {
            addCriterion("modtime between", value1, value2, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotBetween(Date value1, Date value2) {
            addCriterion("modtime not between", value1, value2, "modtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pub_waybillset
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 28 16:54:50 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pub_waybillset
     *
     * @mbggenerated Mon Sep 28 16:54:50 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}