package com.jiuyescm.bms.pub.customer.entity;

/**
 * 商家物流商对应关系实体
 * @author zhengyishan
 *
 */
public class CuscarrierRuleEntity {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.id
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.warehouseid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String warehouseid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.customerid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String customerid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.carrierid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String carrierid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.digitalprintflag
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String digitalprintflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.expressprintstyle
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String expressprintstyle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.delflag
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private Integer delflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.monpayaccount
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String monpayaccount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.pickupperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String pickupperson;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.identitytype
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String identitytype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.IDNO
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String idno;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.sendname
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String sendname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.sendcomp
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String sendcomp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.sendtel
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String sendtel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.sendmobile
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String sendmobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.sendaddress
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String sendaddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.sendzipcode
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String sendzipcode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.regionid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String regionid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.itf_url
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String itfUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.crepersonid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String crepersonid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.creperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String creperson;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.cretime
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private java.sql.Timestamp cretime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.modpersonid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String modpersonid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.modperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private String modperson;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cuscarrier_rule.modtime
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	private java.sql.Timestamp modtime;
	
	//运单生成规则
	private String expressaddrule;

	private String sendcustomercode; //发件客户编号
	private String sendcheckcode; //发件客户校验码
	
	private String ytoclientid; //圆通账号
	private String ytoparternid; //圆通秘钥
	/**圆通要求字段**/
	private String province;// 省
	private String city;// 市
	private String district;// 区（县）
	
	private Integer paymethod;//顺丰付款方式：1:寄方付2:收方付3:第三方付
	private String expresstype;//顺丰快件产品类别
	private String thirdpayadress;//顺丰添加转第三方地区
	
	private String partner; //账号
	private String pass; //秘钥
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.warehouseid
	 * 
	 * @return the value of pub_cuscarrier_rule.warehouseid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getWarehouseid() {
		return warehouseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.warehouseid
	 * 
	 * @param warehouseid
	 *            the value for pub_cuscarrier_rule.warehouseid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setWarehouseid(String warehouseid) {
		this.warehouseid = warehouseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.customerid
	 * 
	 * @return the value of pub_cuscarrier_rule.customerid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.customerid
	 * 
	 * @param customerid
	 *            the value for pub_cuscarrier_rule.customerid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.carrierid
	 * 
	 * @return the value of pub_cuscarrier_rule.carrierid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getCarrierid() {
		return carrierid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.carrierid
	 * 
	 * @param carrierid
	 *            the value for pub_cuscarrier_rule.carrierid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setCarrierid(String carrierid) {
		this.carrierid = carrierid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.digitalprintflag
	 * 
	 * @return the value of pub_cuscarrier_rule.digitalprintflag
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getDigitalprintflag() {
		return digitalprintflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.digitalprintflag
	 * 
	 * @param digitalprintflag
	 *            the value for pub_cuscarrier_rule.digitalprintflag
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setDigitalprintflag(String digitalprintflag) {
		this.digitalprintflag = digitalprintflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.expressprintstyle
	 * 
	 * @return the value of pub_cuscarrier_rule.expressprintstyle
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getExpressprintstyle() {
		return expressprintstyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.expressprintstyle
	 * 
	 * @param expressprintstyle
	 *            the value for pub_cuscarrier_rule.expressprintstyle
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setExpressprintstyle(String expressprintstyle) {
		this.expressprintstyle = expressprintstyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.delflag
	 * 
	 * @return the value of pub_cuscarrier_rule.delflag
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public Integer getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.delflag
	 * 
	 * @param delflag
	 *            the value for pub_cuscarrier_rule.delflag
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setDelflag(Integer delflag) {
		this.delflag = delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.monpayaccount
	 * 
	 * @return the value of pub_cuscarrier_rule.monpayaccount
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getMonpayaccount() {
		return monpayaccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.monpayaccount
	 * 
	 * @param monpayaccount
	 *            the value for pub_cuscarrier_rule.monpayaccount
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setMonpayaccount(String monpayaccount) {
		this.monpayaccount = monpayaccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.pickupperson
	 * 
	 * @return the value of pub_cuscarrier_rule.pickupperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getPickupperson() {
		return pickupperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.pickupperson
	 * 
	 * @param pickupperson
	 *            the value for pub_cuscarrier_rule.pickupperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setPickupperson(String pickupperson) {
		this.pickupperson = pickupperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.identitytype
	 * 
	 * @return the value of pub_cuscarrier_rule.identitytype
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getIdentitytype() {
		return identitytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.identitytype
	 * 
	 * @param identitytype
	 *            the value for pub_cuscarrier_rule.identitytype
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setIdentitytype(String identitytype) {
		this.identitytype = identitytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.IDNO
	 * 
	 * @return the value of pub_cuscarrier_rule.IDNO
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getIdno() {
		return idno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.IDNO
	 * 
	 * @param idno
	 *            the value for pub_cuscarrier_rule.IDNO
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.sendname
	 * 
	 * @return the value of pub_cuscarrier_rule.sendname
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getSendname() {
		return sendname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.sendname
	 * 
	 * @param sendname
	 *            the value for pub_cuscarrier_rule.sendname
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setSendname(String sendname) {
		this.sendname = sendname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.sendcomp
	 * 
	 * @return the value of pub_cuscarrier_rule.sendcomp
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getSendcomp() {
		return sendcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.sendcomp
	 * 
	 * @param sendcomp
	 *            the value for pub_cuscarrier_rule.sendcomp
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setSendcomp(String sendcomp) {
		this.sendcomp = sendcomp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.sendtel
	 * 
	 * @return the value of pub_cuscarrier_rule.sendtel
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getSendtel() {
		return sendtel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.sendtel
	 * 
	 * @param sendtel
	 *            the value for pub_cuscarrier_rule.sendtel
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setSendtel(String sendtel) {
		this.sendtel = sendtel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.sendmobile
	 * 
	 * @return the value of pub_cuscarrier_rule.sendmobile
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getSendmobile() {
		return sendmobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.sendmobile
	 * 
	 * @param sendmobile
	 *            the value for pub_cuscarrier_rule.sendmobile
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setSendmobile(String sendmobile) {
		this.sendmobile = sendmobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.sendaddress
	 * 
	 * @return the value of pub_cuscarrier_rule.sendaddress
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getSendaddress() {
		return sendaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.sendaddress
	 * 
	 * @param sendaddress
	 *            the value for pub_cuscarrier_rule.sendaddress
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setSendaddress(String sendaddress) {
		this.sendaddress = sendaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.sendzipcode
	 * 
	 * @return the value of pub_cuscarrier_rule.sendzipcode
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getSendzipcode() {
		return sendzipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.sendzipcode
	 * 
	 * @param sendzipcode
	 *            the value for pub_cuscarrier_rule.sendzipcode
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setSendzipcode(String sendzipcode) {
		this.sendzipcode = sendzipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.regionid
	 * 
	 * @return the value of pub_cuscarrier_rule.regionid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getRegionid() {
		return regionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.regionid
	 * 
	 * @param regionid
	 *            the value for pub_cuscarrier_rule.regionid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setRegionid(String regionid) {
		this.regionid = regionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.itf_url
	 * 
	 * @return the value of pub_cuscarrier_rule.itf_url
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getItfUrl() {
		return itfUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.itf_url
	 * 
	 * @param itfUrl
	 *            the value for pub_cuscarrier_rule.itf_url
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setItfUrl(String itfUrl) {
		this.itfUrl = itfUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.crepersonid
	 * 
	 * @return the value of pub_cuscarrier_rule.crepersonid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getCrepersonid() {
		return crepersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.crepersonid
	 * 
	 * @param crepersonid
	 *            the value for pub_cuscarrier_rule.crepersonid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setCrepersonid(String crepersonid) {
		this.crepersonid = crepersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.creperson
	 * 
	 * @return the value of pub_cuscarrier_rule.creperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getCreperson() {
		return creperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.creperson
	 * 
	 * @param creperson
	 *            the value for pub_cuscarrier_rule.creperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setCreperson(String creperson) {
		this.creperson = creperson;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.modpersonid
	 * 
	 * @return the value of pub_cuscarrier_rule.modpersonid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getModpersonid() {
		return modpersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.modpersonid
	 * 
	 * @param modpersonid
	 *            the value for pub_cuscarrier_rule.modpersonid
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setModpersonid(String modpersonid) {
		this.modpersonid = modpersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cuscarrier_rule.modperson
	 * 
	 * @return the value of pub_cuscarrier_rule.modperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public String getModperson() {
		return modperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cuscarrier_rule.modperson
	 * 
	 * @param modperson
	 *            the value for pub_cuscarrier_rule.modperson
	 * 
	 * @mbggenerated Tue Sep 08 17:07:03 CST 2015
	 */
	public void setModperson(String modperson) {
		this.modperson = modperson;
	}

	public java.sql.Timestamp getCretime() {
		return cretime;
	}

	public void setCretime(java.sql.Timestamp cretime) {
		this.cretime = cretime;
	}

	public java.sql.Timestamp getModtime() {
		return modtime;
	}

	public void setModtime(java.sql.Timestamp modtime) {
		this.modtime = modtime;
	}

	public String getExpressaddrule() {
		return expressaddrule;
	}

	public void setExpressaddrule(String expressaddrule) {
		this.expressaddrule = expressaddrule;
	}

	public String getSendcustomercode() {
		return sendcustomercode;
	}

	public void setSendcustomercode(String sendcustomercode) {
		this.sendcustomercode = sendcustomercode;
	}

	public String getSendcheckcode() {
		return sendcheckcode;
	}

	public void setSendcheckcode(String sendcheckcode) {
		this.sendcheckcode = sendcheckcode;
	}

	public String getYtoclientid() {
		return ytoclientid;
	}

	public void setYtoclientid(String ytoclientid) {
		this.ytoclientid = ytoclientid;
	}

	public String getYtoparternid() {
		return ytoparternid;
	}

	public void setYtoparternid(String ytoparternid) {
		this.ytoparternid = ytoparternid;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public Integer getPaymethod() {
		return paymethod;
	}

	public void setPaymethod(Integer paymethod) {
		this.paymethod = paymethod;
	}

	public String getExpresstype() {
		return expresstype;
	}

	public void setExpresstype(String expresstype) {
		this.expresstype = expresstype;
	}

	public String getThirdpayadress() {
		return thirdpayadress;
	}

	public void setThirdpayadress(String thirdpayadress) {
		this.thirdpayadress = thirdpayadress;
	}

	public String getPartner() {
		return partner;
	}

	public void setPartner(String partner) {
		this.partner = partner;
	}

	public String getPass() {
		return pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}
	
}