package com.jiuyescm.bms.pub.customer.entity;

import java.util.Date;

import com.jiuyescm.bms.pub.project.entity.ProjectEntity;

/**
 * 商家项目关系实体
 * 
 * @author zhengyishan
 * 
 */
public class CusprojectRuleEntity {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.id
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.customerid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private String customerid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.projectid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private String projectid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.delflag
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private Integer delflag = 0;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.creperson
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private String creperson;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.crepersonid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private String crepersonid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.cretime
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private Date cretime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.modperson
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private String modperson;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.modpersonid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private String modpersonid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_cusproject_rule.modtime
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	private Date modtime;

	/******************* 关联对象 *******************/
	//商家
	private CustomerEntity customer;
	//项目
	private ProjectEntity project;
	
	//商家名称/简称
	private String customername;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.id
	 * 
	 * @return the value of pub_cusproject_rule.id
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.id
	 * 
	 * @param id
	 *            the value for pub_cusproject_rule.id
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.customerid
	 * 
	 * @return the value of pub_cusproject_rule.customerid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.customerid
	 * 
	 * @param customerid
	 *            the value for pub_cusproject_rule.customerid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.projectid
	 * 
	 * @return the value of pub_cusproject_rule.projectid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public String getProjectid() {
		return projectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.projectid
	 * 
	 * @param projectid
	 *            the value for pub_cusproject_rule.projectid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setProjectid(String projectid) {
		this.projectid = projectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.delflag
	 * 
	 * @return the value of pub_cusproject_rule.delflag
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public Integer getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.delflag
	 * 
	 * @param delflag
	 *            the value for pub_cusproject_rule.delflag
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setDelflag(Integer delflag) {
		this.delflag = delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.creperson
	 * 
	 * @return the value of pub_cusproject_rule.creperson
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public String getCreperson() {
		return creperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.creperson
	 * 
	 * @param creperson
	 *            the value for pub_cusproject_rule.creperson
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setCreperson(String creperson) {
		this.creperson = creperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.crepersonid
	 * 
	 * @return the value of pub_cusproject_rule.crepersonid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public String getCrepersonid() {
		return crepersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.crepersonid
	 * 
	 * @param crepersonid
	 *            the value for pub_cusproject_rule.crepersonid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setCrepersonid(String crepersonid) {
		this.crepersonid = crepersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.cretime
	 * 
	 * @return the value of pub_cusproject_rule.cretime
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public Date getCretime() {
		return cretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.cretime
	 * 
	 * @param cretime
	 *            the value for pub_cusproject_rule.cretime
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setCretime(Date cretime) {
		this.cretime = cretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.modperson
	 * 
	 * @return the value of pub_cusproject_rule.modperson
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public String getModperson() {
		return modperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.modperson
	 * 
	 * @param modperson
	 *            the value for pub_cusproject_rule.modperson
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setModperson(String modperson) {
		this.modperson = modperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.modpersonid
	 * 
	 * @return the value of pub_cusproject_rule.modpersonid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public String getModpersonid() {
		return modpersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.modpersonid
	 * 
	 * @param modpersonid
	 *            the value for pub_cusproject_rule.modpersonid
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setModpersonid(String modpersonid) {
		this.modpersonid = modpersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_cusproject_rule.modtime
	 * 
	 * @return the value of pub_cusproject_rule.modtime
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public Date getModtime() {
		return modtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_cusproject_rule.modtime
	 * 
	 * @param modtime
	 *            the value for pub_cusproject_rule.modtime
	 * 
	 * @mbggenerated Tue Sep 08 16:50:16 CST 2015
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}
	
	public CustomerEntity getCustomer() {
		return customer;
	}

	public void setCustomer(CustomerEntity customer) {
		this.customer = customer;
	}

	public ProjectEntity getProject() {
		return project;
	}

	public void setProject(ProjectEntity project) {
		this.project = project;
	}

	public String getCustomername() {
		return customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}
	
	
}