package com.jiuyescm.bms.pub.customer.entity;

import java.util.Date;

import com.jiuyescm.cfm.domain.IEntity;

public class CustomerEntity implements IEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = -8648009794742944506L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.customerid
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String customerid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.orgid
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String orgid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.customercode
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String customercode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.shortname
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String shortname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.customername
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String customername;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.linkman
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String linkman;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.address
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.tel
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String tel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.mobile
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.zipcode
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String zipcode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.remark
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String remark;

	private Integer delflag = 0; // 0:未作废;1：已作废

	private String creperson;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.cretime
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private Date cretime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.modperson
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private String modperson;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_customer.modtime
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	private Date modtime;
	
	private String confirmbatchflag; //分批收货标记 0：否
	private String uploadExpressnumStatus; //设置同步运单是的订单状态
	
	private String packagedesc;//包装要求
	private String province;//省份
	private String city;//市
	private String district;//区
	private String area;//所属区域
	private String level;//商家等级
	private String type1;//类型1
	private String type2;//类型2
	private String type3;//类型3
	private Date signdate;//签约日期
	private String mainProduct; //主营产品
	private String productInfo; //产品描述
	private String companyProfile; //公司简介
	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getLevel() {
		return level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getType1() {
		return type1;
	}

	public void setType1(String type1) {
		this.type1 = type1;
	}

	public String getType2() {
		return type2;
	}

	public void setType2(String type2) {
		this.type2 = type2;
	}

	public String getType3() {
		return type3;
	}

	public void setType3(String type3) {
		this.type3 = type3;
	}

	public Date getSigndate() {
		return signdate;
	}

	public void setSigndate(Date signdate) {
		this.signdate = signdate;
	}

	public String getMainProduct() {
		return mainProduct;
	}

	public void setMainProduct(String mainProduct) {
		this.mainProduct = mainProduct;
	}

	public String getProductInfo() {
		return productInfo;
	}

	public void setProductInfo(String productInfo) {
		this.productInfo = productInfo;
	}

	public String getCompanyProfile() {
		return companyProfile;
	}

	public void setCompanyProfile(String companyProfile) {
		this.companyProfile = companyProfile;
	}

	public String getProjectContents() {
		return projectContents;
	}

	public void setProjectContents(String projectContents) {
		this.projectContents = projectContents;
	}

	private String projectContents; //项目合作内容

	public String getPackagedesc() {
		return packagedesc;
	}

	public void setPackagedesc(String packagedesc) {
		this.packagedesc = packagedesc;
	}

	public String getConfirmbatchflag() {
		return confirmbatchflag;
	}

	public void setConfirmbatchflag(String confirmbatchflag) {
		this.confirmbatchflag = confirmbatchflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.customerid
	 * 
	 * @return the value of pub_customer.customerid
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.customerid
	 * 
	 * @param customerid
	 *            the value for pub_customer.customerid
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.orgid
	 * 
	 * @return the value of pub_customer.orgid
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getOrgid() {
		return orgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.orgid
	 * 
	 * @param orgid
	 *            the value for pub_customer.orgid
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.customercode
	 * 
	 * @return the value of pub_customer.customercode
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getCustomercode() {
		return customercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.customercode
	 * 
	 * @param customercode
	 *            the value for pub_customer.customercode
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setCustomercode(String customercode) {
		this.customercode = customercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.shortname
	 * 
	 * @return the value of pub_customer.shortname
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getShortname() {
		return shortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.shortname
	 * 
	 * @param shortname
	 *            the value for pub_customer.shortname
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.customername
	 * 
	 * @return the value of pub_customer.customername
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getCustomername() {
		return customername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.customername
	 * 
	 * @param customername
	 *            the value for pub_customer.customername
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setCustomername(String customername) {
		this.customername = customername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.linkman
	 * 
	 * @return the value of pub_customer.linkman
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.linkman
	 * 
	 * @param linkman
	 *            the value for pub_customer.linkman
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.address
	 * 
	 * @return the value of pub_customer.address
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.address
	 * 
	 * @param address
	 *            the value for pub_customer.address
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.tel
	 * 
	 * @return the value of pub_customer.tel
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.tel
	 * 
	 * @param tel
	 *            the value for pub_customer.tel
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.mobile
	 * 
	 * @return the value of pub_customer.mobile
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.mobile
	 * 
	 * @param mobile
	 *            the value for pub_customer.mobile
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.zipcode
	 * 
	 * @return the value of pub_customer.zipcode
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.zipcode
	 * 
	 * @param zipcode
	 *            the value for pub_customer.zipcode
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.remark
	 * 
	 * @return the value of pub_customer.remark
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.remark
	 * 
	 * @param remark
	 *            the value for pub_customer.remark
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.delflag
	 * 
	 * @return the value of pub_customer.delflag
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public Integer getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.delflag
	 * 
	 * @param delflag
	 *            the value for pub_customer.delflag
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setDelflag(Integer delflag) {
		this.delflag = delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.creperson
	 * 
	 * @return the value of pub_customer.creperson
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getCreperson() {
		return creperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.creperson
	 * 
	 * @param creperson
	 *            the value for pub_customer.creperson
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setCreperson(String creperson) {
		this.creperson = creperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.cretime
	 * 
	 * @return the value of pub_customer.cretime
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public Date getCretime() {
		return cretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.cretime
	 * 
	 * @param cretime
	 *            the value for pub_customer.cretime
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setCretime(Date cretime) {
		this.cretime = cretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.modperson
	 * 
	 * @return the value of pub_customer.modperson
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public String getModperson() {
		return modperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.modperson
	 * 
	 * @param modperson
	 *            the value for pub_customer.modperson
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setModperson(String modperson) {
		this.modperson = modperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_customer.modtime
	 * 
	 * @return the value of pub_customer.modtime
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public Date getModtime() {
		return modtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_customer.modtime
	 * 
	 * @param modtime
	 *            the value for pub_customer.modtime
	 * 
	 * @mbggenerated Mon Sep 07 14:40:25 CST 2015
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}

	public String getUploadExpressnumStatus() {
		return uploadExpressnumStatus;
	}

	public void setUploadExpressnumStatus(String uploadExpressnumStatus) {
		this.uploadExpressnumStatus = uploadExpressnumStatus;
	}
	
	
}