package com.jiuyescm.bms.common.datapower.entity;


//数组
public class DatagroupEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.id
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.dgroupid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String dgroupid;  //数据组ID

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.dgroupname
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String dgroupname; //数据组名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.remark
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String remark;  //备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String creperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String crepersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.cretime
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private java.sql.Timestamp cretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.modperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String modperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.modpersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String modpersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup.modtime
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private java.sql.Timestamp modtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup.id
     *
     * @return the value of sys_datagroup.id
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup.id
     *
     * @param id the value for sys_datagroup.id
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup.dgroupid
     *
     * @return the value of sys_datagroup.dgroupid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getDgroupid() {
        return dgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup.dgroupid
     *
     * @param dgroupid the value for sys_datagroup.dgroupid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setDgroupid(String dgroupid) {
        this.dgroupid = dgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup.dgroupname
     *
     * @return the value of sys_datagroup.dgroupname
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getDgroupname() {
        return dgroupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup.dgroupname
     *
     * @param dgroupname the value for sys_datagroup.dgroupname
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setDgroupname(String dgroupname) {
        this.dgroupname = dgroupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup.remark
     *
     * @return the value of sys_datagroup.remark
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup.remark
     *
     * @param remark the value for sys_datagroup.remark
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup.creperson
     *
     * @return the value of sys_datagroup.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getCreperson() {
        return creperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup.creperson
     *
     * @param creperson the value for sys_datagroup.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setCreperson(String creperson) {
        this.creperson = creperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup.crepersonid
     *
     * @return the value of sys_datagroup.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getCrepersonid() {
        return crepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup.crepersonid
     *
     * @param crepersonid the value for sys_datagroup.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setCrepersonid(String crepersonid) {
        this.crepersonid = crepersonid;
    }

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup.modperson
     *
     * @return the value of sys_datagroup.modperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getModperson() {
        return modperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup.modperson
     *
     * @param modperson the value for sys_datagroup.modperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setModperson(String modperson) {
        this.modperson = modperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup.modpersonid
     *
     * @return the value of sys_datagroup.modpersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getModpersonid() {
        return modpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup.modpersonid
     *
     * @param modpersonid the value for sys_datagroup.modpersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setModpersonid(String modpersonid) {
        this.modpersonid = modpersonid;
    }

	public java.sql.Timestamp getCretime() {
		return cretime;
	}

	public void setCretime(java.sql.Timestamp cretime) {
		this.cretime = cretime;
	}

	public java.sql.Timestamp getModtime() {
		return modtime;
	}

	public void setModtime(java.sql.Timestamp modtime) {
		this.modtime = modtime;
	}

    
}