package com.jiuyescm.bms.common.datapower.entity;

//数组与仓库相关联
public class DatagroupWarehouseEntity  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_warehouse.dgroupid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String dgroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_warehouse.warehouseid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String warehouseid;
    
    private String warehousename;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_warehouse.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String creperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_warehouse.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String crepersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_warehouse.cretime
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private java.sql.Timestamp cretime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup_warehouse.creperson
     *
     * @return the value of sys_datagroup_warehouse.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getCreperson() {
        return creperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup_warehouse.creperson
     *
     * @param creperson the value for sys_datagroup_warehouse.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setCreperson(String creperson) {
        this.creperson = creperson;
    }

    public String getCrepersonid() {
        return crepersonid;
    }

    public void setCrepersonid(String crepersonid) {
        this.crepersonid = crepersonid;
    }

	public java.sql.Timestamp getCretime() {
		return cretime;
	}

	public void setCretime(java.sql.Timestamp cretime) {
		this.cretime = cretime;
	}

	public String getDgroupid() {
		return dgroupid;
	}

	public void setDgroupid(String dgroupid) {
		this.dgroupid = dgroupid;
	}

	public String getWarehouseid() {
		return warehouseid;
	}

	public void setWarehouseid(String warehouseid) {
		this.warehouseid = warehouseid;
	}

	public String getWarehousename() {
		return warehousename;
	}

	public void setWarehousename(String warehousename) {
		this.warehousename = warehousename;
	}
	

    
}