package com.jiuyescm.bms.common.datapower.entity;

//数组与商家相关联
public class DatagroupCustomerEntity {
	
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_customer.customerid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String customerid;
    
    private String customername; //商家简称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_customer.dgroupid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String dgroupid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_customer.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String creperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_customer.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String crepersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datagroup_customer.cretime
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
     private java.sql.Timestamp cretime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup_customer.creperson
     *
     * @return the value of sys_datagroup_customer.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getCreperson() {
        return creperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup_customer.creperson
     *
     * @param creperson the value for sys_datagroup_customer.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setCreperson(String creperson) {
        this.creperson = creperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datagroup_customer.crepersonid
     *
     * @return the value of sys_datagroup_customer.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getCrepersonid() {
        return crepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datagroup_customer.crepersonid
     *
     * @param crepersonid the value for sys_datagroup_customer.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setCrepersonid(String crepersonid) {
        this.crepersonid = crepersonid;
    }

   

	public java.sql.Timestamp getCretime() {
		return cretime;
	}

	public void setCretime(java.sql.Timestamp cretime) {
		this.cretime = cretime;
	}

	public String getCustomerid() {
		return customerid;
	}

	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	public String getDgroupid() {
		return dgroupid;
	}

	public void setDgroupid(String dgroupid) {
		this.dgroupid = dgroupid;
	}

	public String getCustomername() {
		return customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}
	
    
}