package com.jiuyescm.bms.common.datapower.entity;

import java.util.Date;

//用户与数组权限
public class UserLimitgroupEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_limitgroup.id
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_limitgroup.userid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String userid;
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_limitgroup.groupid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_limitgroup.grouptype
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String grouptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_limitgroup.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String creperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_limitgroup.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private String crepersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_limitgroup.cretime
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    private Date cretime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_limitgroup.id
     *
     * @return the value of sys_user_limitgroup.id
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_limitgroup.id
     *
     * @param id the value for sys_user_limitgroup.id
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_limitgroup.userid
     *
     * @return the value of sys_user_limitgroup.userid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_limitgroup.userid
     *
     * @param userid the value for sys_user_limitgroup.userid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_limitgroup.groupid
     *
     * @return the value of sys_user_limitgroup.groupid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_limitgroup.groupid
     *
     * @param groupid the value for sys_user_limitgroup.groupid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_limitgroup.grouptype
     *
     * @return the value of sys_user_limitgroup.grouptype
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getGrouptype() {
        return grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_limitgroup.grouptype
     *
     * @param grouptype the value for sys_user_limitgroup.grouptype
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setGrouptype(String grouptype) {
        this.grouptype = grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_limitgroup.creperson
     *
     * @return the value of sys_user_limitgroup.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getCreperson() {
        return creperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_limitgroup.creperson
     *
     * @param creperson the value for sys_user_limitgroup.creperson
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setCreperson(String creperson) {
        this.creperson = creperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_limitgroup.crepersonid
     *
     * @return the value of sys_user_limitgroup.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public String getCrepersonid() {
        return crepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_limitgroup.crepersonid
     *
     * @param crepersonid the value for sys_user_limitgroup.crepersonid
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setCrepersonid(String crepersonid) {
        this.crepersonid = crepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_limitgroup.cretime
     *
     * @return the value of sys_user_limitgroup.cretime
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public Date getCretime() {
        return cretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_limitgroup.cretime
     *
     * @param cretime the value for sys_user_limitgroup.cretime
     *
     * @mbggenerated Wed Nov 18 19:30:56 CST 2015
     */
    public void setCretime(Date cretime) {
        this.cretime = cretime;
    }

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
    
}