package com.jiuyescm.bms.pub.excel.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OmsExcelimpEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.currentno
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String currentno;
    
    private Integer rowno; //行号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col09
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col10
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col11
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col12
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col13
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col14
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col15
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col16
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col17
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col18
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col19
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col20
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col20;
    
    private String col21;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col22
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col23
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col24
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col25
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col26
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col27
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col28
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col29
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col30
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col31
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col31;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col32
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col32;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col33
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col33;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col34
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col34;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col35
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col35;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col36
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col36;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col37
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col37;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col38
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col38;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col39
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col39;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col40
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col40;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col41
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col41;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col42
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col42;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col43
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col43;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col44
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col44;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.col45
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private String col45;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.date01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date date01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.date02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date date02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.date03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date date03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.date04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date date04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.date05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date date05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.date06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date date06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.datetime01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date datetime01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.datetime02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date datetime02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.datetime03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date datetime03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.datetime04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date datetime04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.datetime05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date datetime05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.datetime06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Date datetime06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.num01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Integer num01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.num02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Integer num02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.num03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Integer num03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.num04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Integer num04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.num05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Integer num05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.num06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Integer num06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.num07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Integer num07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.num08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private Integer num08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.decnum01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private BigDecimal decnum01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.decnum02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private BigDecimal decnum02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.decnum03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private BigDecimal decnum03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.decnum04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private BigDecimal decnum04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.decnum05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private BigDecimal decnum05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.decnum06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private BigDecimal decnum06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.decnum07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private BigDecimal decnum07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_omsexcel_imp.decnum08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    private BigDecimal decnum08;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.currentno
     *
     * @return the value of pub_omsexcel_imp.currentno
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCurrentno() {
        return currentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.currentno
     *
     * @param currentno the value for pub_omsexcel_imp.currentno
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCurrentno(String currentno) {
        this.currentno = currentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col01
     *
     * @return the value of pub_omsexcel_imp.col01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol01() {
        return col01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col01
     *
     * @param col01 the value for pub_omsexcel_imp.col01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol01(String col01) {
        this.col01 = col01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col02
     *
     * @return the value of pub_omsexcel_imp.col02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol02() {
        return col02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col02
     *
     * @param col02 the value for pub_omsexcel_imp.col02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol02(String col02) {
        this.col02 = col02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col03
     *
     * @return the value of pub_omsexcel_imp.col03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol03() {
        return col03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col03
     *
     * @param col03 the value for pub_omsexcel_imp.col03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol03(String col03) {
        this.col03 = col03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col04
     *
     * @return the value of pub_omsexcel_imp.col04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol04() {
        return col04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col04
     *
     * @param col04 the value for pub_omsexcel_imp.col04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol04(String col04) {
        this.col04 = col04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col05
     *
     * @return the value of pub_omsexcel_imp.col05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol05() {
        return col05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col05
     *
     * @param col05 the value for pub_omsexcel_imp.col05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol05(String col05) {
        this.col05 = col05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col06
     *
     * @return the value of pub_omsexcel_imp.col06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol06() {
        return col06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col06
     *
     * @param col06 the value for pub_omsexcel_imp.col06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol06(String col06) {
        this.col06 = col06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col07
     *
     * @return the value of pub_omsexcel_imp.col07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol07() {
        return col07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col07
     *
     * @param col07 the value for pub_omsexcel_imp.col07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol07(String col07) {
        this.col07 = col07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col08
     *
     * @return the value of pub_omsexcel_imp.col08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol08() {
        return col08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col08
     *
     * @param col08 the value for pub_omsexcel_imp.col08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol08(String col08) {
        this.col08 = col08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col09
     *
     * @return the value of pub_omsexcel_imp.col09
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol09() {
        return col09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col09
     *
     * @param col09 the value for pub_omsexcel_imp.col09
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol09(String col09) {
        this.col09 = col09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col10
     *
     * @return the value of pub_omsexcel_imp.col10
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol10() {
        return col10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col10
     *
     * @param col10 the value for pub_omsexcel_imp.col10
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol10(String col10) {
        this.col10 = col10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col11
     *
     * @return the value of pub_omsexcel_imp.col11
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol11() {
        return col11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col11
     *
     * @param col11 the value for pub_omsexcel_imp.col11
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol11(String col11) {
        this.col11 = col11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col12
     *
     * @return the value of pub_omsexcel_imp.col12
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol12() {
        return col12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col12
     *
     * @param col12 the value for pub_omsexcel_imp.col12
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol12(String col12) {
        this.col12 = col12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col13
     *
     * @return the value of pub_omsexcel_imp.col13
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol13() {
        return col13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col13
     *
     * @param col13 the value for pub_omsexcel_imp.col13
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol13(String col13) {
        this.col13 = col13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col14
     *
     * @return the value of pub_omsexcel_imp.col14
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol14() {
        return col14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col14
     *
     * @param col14 the value for pub_omsexcel_imp.col14
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol14(String col14) {
        this.col14 = col14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col15
     *
     * @return the value of pub_omsexcel_imp.col15
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol15() {
        return col15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col15
     *
     * @param col15 the value for pub_omsexcel_imp.col15
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol15(String col15) {
        this.col15 = col15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col16
     *
     * @return the value of pub_omsexcel_imp.col16
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol16() {
        return col16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col16
     *
     * @param col16 the value for pub_omsexcel_imp.col16
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol16(String col16) {
        this.col16 = col16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col17
     *
     * @return the value of pub_omsexcel_imp.col17
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol17() {
        return col17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col17
     *
     * @param col17 the value for pub_omsexcel_imp.col17
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol17(String col17) {
        this.col17 = col17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col18
     *
     * @return the value of pub_omsexcel_imp.col18
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol18() {
        return col18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col18
     *
     * @param col18 the value for pub_omsexcel_imp.col18
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol18(String col18) {
        this.col18 = col18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col19
     *
     * @return the value of pub_omsexcel_imp.col19
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol19() {
        return col19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col19
     *
     * @param col19 the value for pub_omsexcel_imp.col19
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol19(String col19) {
        this.col19 = col19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col20
     *
     * @return the value of pub_omsexcel_imp.col20
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol20() {
        return col20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col20
     *
     * @param col20 the value for pub_omsexcel_imp.col20
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol20(String col20) {
        this.col20 = col20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col22
     *
     * @return the value of pub_omsexcel_imp.col22
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol22() {
        return col22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col22
     *
     * @param col22 the value for pub_omsexcel_imp.col22
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol22(String col22) {
        this.col22 = col22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col23
     *
     * @return the value of pub_omsexcel_imp.col23
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol23() {
        return col23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col23
     *
     * @param col23 the value for pub_omsexcel_imp.col23
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol23(String col23) {
        this.col23 = col23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col24
     *
     * @return the value of pub_omsexcel_imp.col24
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol24() {
        return col24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col24
     *
     * @param col24 the value for pub_omsexcel_imp.col24
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol24(String col24) {
        this.col24 = col24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col25
     *
     * @return the value of pub_omsexcel_imp.col25
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol25() {
        return col25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col25
     *
     * @param col25 the value for pub_omsexcel_imp.col25
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol25(String col25) {
        this.col25 = col25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col26
     *
     * @return the value of pub_omsexcel_imp.col26
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol26() {
        return col26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col26
     *
     * @param col26 the value for pub_omsexcel_imp.col26
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol26(String col26) {
        this.col26 = col26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col27
     *
     * @return the value of pub_omsexcel_imp.col27
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol27() {
        return col27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col27
     *
     * @param col27 the value for pub_omsexcel_imp.col27
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol27(String col27) {
        this.col27 = col27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col28
     *
     * @return the value of pub_omsexcel_imp.col28
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol28() {
        return col28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col28
     *
     * @param col28 the value for pub_omsexcel_imp.col28
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol28(String col28) {
        this.col28 = col28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col29
     *
     * @return the value of pub_omsexcel_imp.col29
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol29() {
        return col29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col29
     *
     * @param col29 the value for pub_omsexcel_imp.col29
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol29(String col29) {
        this.col29 = col29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col30
     *
     * @return the value of pub_omsexcel_imp.col30
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol30() {
        return col30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col30
     *
     * @param col30 the value for pub_omsexcel_imp.col30
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol30(String col30) {
        this.col30 = col30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col31
     *
     * @return the value of pub_omsexcel_imp.col31
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol31() {
        return col31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col31
     *
     * @param col31 the value for pub_omsexcel_imp.col31
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol31(String col31) {
        this.col31 = col31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col32
     *
     * @return the value of pub_omsexcel_imp.col32
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol32() {
        return col32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col32
     *
     * @param col32 the value for pub_omsexcel_imp.col32
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol32(String col32) {
        this.col32 = col32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col33
     *
     * @return the value of pub_omsexcel_imp.col33
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol33() {
        return col33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col33
     *
     * @param col33 the value for pub_omsexcel_imp.col33
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol33(String col33) {
        this.col33 = col33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col34
     *
     * @return the value of pub_omsexcel_imp.col34
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol34() {
        return col34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col34
     *
     * @param col34 the value for pub_omsexcel_imp.col34
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol34(String col34) {
        this.col34 = col34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col35
     *
     * @return the value of pub_omsexcel_imp.col35
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol35() {
        return col35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col35
     *
     * @param col35 the value for pub_omsexcel_imp.col35
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol35(String col35) {
        this.col35 = col35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col36
     *
     * @return the value of pub_omsexcel_imp.col36
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol36() {
        return col36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col36
     *
     * @param col36 the value for pub_omsexcel_imp.col36
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol36(String col36) {
        this.col36 = col36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col37
     *
     * @return the value of pub_omsexcel_imp.col37
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol37() {
        return col37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col37
     *
     * @param col37 the value for pub_omsexcel_imp.col37
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol37(String col37) {
        this.col37 = col37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col38
     *
     * @return the value of pub_omsexcel_imp.col38
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol38() {
        return col38;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col38
     *
     * @param col38 the value for pub_omsexcel_imp.col38
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol38(String col38) {
        this.col38 = col38;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col39
     *
     * @return the value of pub_omsexcel_imp.col39
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol39() {
        return col39;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col39
     *
     * @param col39 the value for pub_omsexcel_imp.col39
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol39(String col39) {
        this.col39 = col39;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col40
     *
     * @return the value of pub_omsexcel_imp.col40
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol40() {
        return col40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col40
     *
     * @param col40 the value for pub_omsexcel_imp.col40
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol40(String col40) {
        this.col40 = col40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col41
     *
     * @return the value of pub_omsexcel_imp.col41
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol41() {
        return col41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col41
     *
     * @param col41 the value for pub_omsexcel_imp.col41
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol41(String col41) {
        this.col41 = col41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col42
     *
     * @return the value of pub_omsexcel_imp.col42
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol42() {
        return col42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col42
     *
     * @param col42 the value for pub_omsexcel_imp.col42
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol42(String col42) {
        this.col42 = col42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col43
     *
     * @return the value of pub_omsexcel_imp.col43
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol43() {
        return col43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col43
     *
     * @param col43 the value for pub_omsexcel_imp.col43
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol43(String col43) {
        this.col43 = col43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col44
     *
     * @return the value of pub_omsexcel_imp.col44
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol44() {
        return col44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col44
     *
     * @param col44 the value for pub_omsexcel_imp.col44
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol44(String col44) {
        this.col44 = col44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.col45
     *
     * @return the value of pub_omsexcel_imp.col45
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public String getCol45() {
        return col45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.col45
     *
     * @param col45 the value for pub_omsexcel_imp.col45
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setCol45(String col45) {
        this.col45 = col45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.date01
     *
     * @return the value of pub_omsexcel_imp.date01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDate01() {
        return date01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.date01
     *
     * @param date01 the value for pub_omsexcel_imp.date01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDate01(Date date01) {
        this.date01 = date01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.date02
     *
     * @return the value of pub_omsexcel_imp.date02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDate02() {
        return date02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.date02
     *
     * @param date02 the value for pub_omsexcel_imp.date02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDate02(Date date02) {
        this.date02 = date02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.date03
     *
     * @return the value of pub_omsexcel_imp.date03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDate03() {
        return date03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.date03
     *
     * @param date03 the value for pub_omsexcel_imp.date03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDate03(Date date03) {
        this.date03 = date03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.date04
     *
     * @return the value of pub_omsexcel_imp.date04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDate04() {
        return date04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.date04
     *
     * @param date04 the value for pub_omsexcel_imp.date04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDate04(Date date04) {
        this.date04 = date04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.date05
     *
     * @return the value of pub_omsexcel_imp.date05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDate05() {
        return date05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.date05
     *
     * @param date05 the value for pub_omsexcel_imp.date05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDate05(Date date05) {
        this.date05 = date05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.date06
     *
     * @return the value of pub_omsexcel_imp.date06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDate06() {
        return date06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.date06
     *
     * @param date06 the value for pub_omsexcel_imp.date06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDate06(Date date06) {
        this.date06 = date06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.datetime01
     *
     * @return the value of pub_omsexcel_imp.datetime01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDatetime01() {
        return datetime01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.datetime01
     *
     * @param datetime01 the value for pub_omsexcel_imp.datetime01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDatetime01(Date datetime01) {
        this.datetime01 = datetime01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.datetime02
     *
     * @return the value of pub_omsexcel_imp.datetime02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDatetime02() {
        return datetime02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.datetime02
     *
     * @param datetime02 the value for pub_omsexcel_imp.datetime02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDatetime02(Date datetime02) {
        this.datetime02 = datetime02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.datetime03
     *
     * @return the value of pub_omsexcel_imp.datetime03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDatetime03() {
        return datetime03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.datetime03
     *
     * @param datetime03 the value for pub_omsexcel_imp.datetime03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDatetime03(Date datetime03) {
        this.datetime03 = datetime03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.datetime04
     *
     * @return the value of pub_omsexcel_imp.datetime04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDatetime04() {
        return datetime04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.datetime04
     *
     * @param datetime04 the value for pub_omsexcel_imp.datetime04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDatetime04(Date datetime04) {
        this.datetime04 = datetime04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.datetime05
     *
     * @return the value of pub_omsexcel_imp.datetime05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDatetime05() {
        return datetime05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.datetime05
     *
     * @param datetime05 the value for pub_omsexcel_imp.datetime05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDatetime05(Date datetime05) {
        this.datetime05 = datetime05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.datetime06
     *
     * @return the value of pub_omsexcel_imp.datetime06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Date getDatetime06() {
        return datetime06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.datetime06
     *
     * @param datetime06 the value for pub_omsexcel_imp.datetime06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDatetime06(Date datetime06) {
        this.datetime06 = datetime06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.num01
     *
     * @return the value of pub_omsexcel_imp.num01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Integer getNum01() {
        return num01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.num01
     *
     * @param num01 the value for pub_omsexcel_imp.num01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setNum01(Integer num01) {
        this.num01 = num01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.num02
     *
     * @return the value of pub_omsexcel_imp.num02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Integer getNum02() {
        return num02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.num02
     *
     * @param num02 the value for pub_omsexcel_imp.num02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setNum02(Integer num02) {
        this.num02 = num02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.num03
     *
     * @return the value of pub_omsexcel_imp.num03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Integer getNum03() {
        return num03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.num03
     *
     * @param num03 the value for pub_omsexcel_imp.num03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setNum03(Integer num03) {
        this.num03 = num03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.num04
     *
     * @return the value of pub_omsexcel_imp.num04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Integer getNum04() {
        return num04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.num04
     *
     * @param num04 the value for pub_omsexcel_imp.num04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setNum04(Integer num04) {
        this.num04 = num04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.num05
     *
     * @return the value of pub_omsexcel_imp.num05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Integer getNum05() {
        return num05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.num05
     *
     * @param num05 the value for pub_omsexcel_imp.num05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setNum05(Integer num05) {
        this.num05 = num05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.num06
     *
     * @return the value of pub_omsexcel_imp.num06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Integer getNum06() {
        return num06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.num06
     *
     * @param num06 the value for pub_omsexcel_imp.num06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setNum06(Integer num06) {
        this.num06 = num06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.num07
     *
     * @return the value of pub_omsexcel_imp.num07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Integer getNum07() {
        return num07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.num07
     *
     * @param num07 the value for pub_omsexcel_imp.num07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setNum07(Integer num07) {
        this.num07 = num07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.num08
     *
     * @return the value of pub_omsexcel_imp.num08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public Integer getNum08() {
        return num08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.num08
     *
     * @param num08 the value for pub_omsexcel_imp.num08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setNum08(Integer num08) {
        this.num08 = num08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.decnum01
     *
     * @return the value of pub_omsexcel_imp.decnum01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public BigDecimal getDecnum01() {
        return decnum01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.decnum01
     *
     * @param decnum01 the value for pub_omsexcel_imp.decnum01
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDecnum01(BigDecimal decnum01) {
        this.decnum01 = decnum01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.decnum02
     *
     * @return the value of pub_omsexcel_imp.decnum02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public BigDecimal getDecnum02() {
        return decnum02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.decnum02
     *
     * @param decnum02 the value for pub_omsexcel_imp.decnum02
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDecnum02(BigDecimal decnum02) {
        this.decnum02 = decnum02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.decnum03
     *
     * @return the value of pub_omsexcel_imp.decnum03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public BigDecimal getDecnum03() {
        return decnum03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.decnum03
     *
     * @param decnum03 the value for pub_omsexcel_imp.decnum03
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDecnum03(BigDecimal decnum03) {
        this.decnum03 = decnum03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.decnum04
     *
     * @return the value of pub_omsexcel_imp.decnum04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public BigDecimal getDecnum04() {
        return decnum04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.decnum04
     *
     * @param decnum04 the value for pub_omsexcel_imp.decnum04
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDecnum04(BigDecimal decnum04) {
        this.decnum04 = decnum04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.decnum05
     *
     * @return the value of pub_omsexcel_imp.decnum05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public BigDecimal getDecnum05() {
        return decnum05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.decnum05
     *
     * @param decnum05 the value for pub_omsexcel_imp.decnum05
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDecnum05(BigDecimal decnum05) {
        this.decnum05 = decnum05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.decnum06
     *
     * @return the value of pub_omsexcel_imp.decnum06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public BigDecimal getDecnum06() {
        return decnum06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.decnum06
     *
     * @param decnum06 the value for pub_omsexcel_imp.decnum06
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDecnum06(BigDecimal decnum06) {
        this.decnum06 = decnum06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.decnum07
     *
     * @return the value of pub_omsexcel_imp.decnum07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public BigDecimal getDecnum07() {
        return decnum07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.decnum07
     *
     * @param decnum07 the value for pub_omsexcel_imp.decnum07
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDecnum07(BigDecimal decnum07) {
        this.decnum07 = decnum07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_omsexcel_imp.decnum08
     *
     * @return the value of pub_omsexcel_imp.decnum08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public BigDecimal getDecnum08() {
        return decnum08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_omsexcel_imp.decnum08
     *
     * @param decnum08 the value for pub_omsexcel_imp.decnum08
     *
     * @mbggenerated Fri Oct 02 12:13:26 CST 2015
     */
    public void setDecnum08(BigDecimal decnum08) {
        this.decnum08 = decnum08;
    }

	public Integer getRowno() {
		return rowno;
	}

	public void setRowno(Integer rowno) {
		this.rowno = rowno;
	}

	public String getCol21() {
		return col21;
	}

	public void setCol21(String col21) {
		this.col21 = col21;
	}

	
    
}