package com.jiuyescm.bms.common.sequence.entity;

import java.util.ArrayList;
import java.util.List;

public class SequenceEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public SequenceEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdnameIsNull() {
            addCriterion("idname is null");
            return (Criteria) this;
        }

        public Criteria andIdnameIsNotNull() {
            addCriterion("idname is not null");
            return (Criteria) this;
        }

        public Criteria andIdnameEqualTo(String value) {
            addCriterion("idname =", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameNotEqualTo(String value) {
            addCriterion("idname <>", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameGreaterThan(String value) {
            addCriterion("idname >", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameGreaterThanOrEqualTo(String value) {
            addCriterion("idname >=", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameLessThan(String value) {
            addCriterion("idname <", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameLessThanOrEqualTo(String value) {
            addCriterion("idname <=", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameLike(String value) {
            addCriterion("idname like", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameNotLike(String value) {
            addCriterion("idname not like", value, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameIn(List<String> values) {
            addCriterion("idname in", values, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameNotIn(List<String> values) {
            addCriterion("idname not in", values, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameBetween(String value1, String value2) {
            addCriterion("idname between", value1, value2, "idname");
            return (Criteria) this;
        }

        public Criteria andIdnameNotBetween(String value1, String value2) {
            addCriterion("idname not between", value1, value2, "idname");
            return (Criteria) this;
        }

        public Criteria andSeqnumIsNull() {
            addCriterion("seqnum is null");
            return (Criteria) this;
        }

        public Criteria andSeqnumIsNotNull() {
            addCriterion("seqnum is not null");
            return (Criteria) this;
        }

        public Criteria andSeqnumEqualTo(Long value) {
            addCriterion("seqnum =", value, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumNotEqualTo(Long value) {
            addCriterion("seqnum <>", value, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumGreaterThan(Long value) {
            addCriterion("seqnum >", value, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumGreaterThanOrEqualTo(Long value) {
            addCriterion("seqnum >=", value, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumLessThan(Long value) {
            addCriterion("seqnum <", value, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumLessThanOrEqualTo(Long value) {
            addCriterion("seqnum <=", value, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumIn(List<Long> values) {
            addCriterion("seqnum in", values, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumNotIn(List<Long> values) {
            addCriterion("seqnum not in", values, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumBetween(Long value1, Long value2) {
            addCriterion("seqnum between", value1, value2, "seqnum");
            return (Criteria) this;
        }

        public Criteria andSeqnumNotBetween(Long value1, Long value2) {
            addCriterion("seqnum not between", value1, value2, "seqnum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pub_sequence
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 12 15:03:00 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pub_sequence
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}