package com.jiuyescm.bms.common.sequence.entity;

public class SequenceEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_sequence.idname
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    private String idname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_sequence.seqnum
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    private Long seqnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_sequence.idname
     *
     * @return the value of pub_sequence.idname
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public String getIdname() {
        return idname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_sequence.idname
     *
     * @param idname the value for pub_sequence.idname
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public void setIdname(String idname) {
        this.idname = idname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_sequence.seqnum
     *
     * @return the value of pub_sequence.seqnum
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public Long getSeqnum() {
        return seqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_sequence.seqnum
     *
     * @param seqnum the value for pub_sequence.seqnum
     *
     * @mbggenerated Mon Oct 12 15:03:00 CST 2015
     */
    public void setSeqnum(Long seqnum) {
        this.seqnum = seqnum;
    }
}